### ISSUE TITLE
can't create 2 connections

### ISSUE THREAD

**Issue by Skeyelab** [jasny/db-mysql#6]
I'm having trouble creating 2 connections with your class.  Is this possible?

**Comment by jasny** [comment]
Yes, it should just work.

``` php
use Jasny\MySQL\DB;

$db1 = new DB($host1, $user1, $pass1, $dbname1);
$db2 = new DB($host2, $user2, $pass2, $dbname2);
```

Note that only `$db1` is available as `DB::conn()`.

---

That said, I recommend switching to the full featured [jasny/db](/jasny/db) library if possible. I will deprecate this DB-MySQL and DBQuery-MySQL in favor of jasny/db and [jasny/dbquery](/jasny/dbquery) very soon.

With jasny/db you can use the multiton pattern.

``` php
use Jasny\DB\MySQL\Connection as DB;

new DB($host1, $user1, $pass1, $dbname1);
DB::conn()->query("SELECT * FROM foo");

$db_other = new DB($host2, $user2, $pass2, $dbname2);
$db_other->useAs('other');
DB::conn('other')->query("SELECT * FROM bar");
```

jasny/db requres php 5.4 or newer.

**Comment by Skeyelab** [comment]
Thanks... it turns out one of my DB's was behind a firewall... duh.
